FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
COPY packages/*/package*.json ./packages/*/

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]
