export type UserRole = 'owner' | 'admin' | 'manager' | 'cleaner' | 'subcontractor';

export interface RolePermissions {
  [key: string]: boolean;
}

export const rolePermissions: Record<UserRole, RolePermissions> = {
  owner: {
    all: true,
    users: true,
    users_read: true,
    users_write: true,
    settings: true,
    settings_read: true,
    settings_write: true,
    billing: true,
    pricing_read: true,
    pricing_write: true,
    teams_read: true,
    teams_write: true,
    proposal_templates_read: true,
    proposal_templates_write: true,
    area_types_manage: true,
    lead_sources_read: true,
    lead_sources_write: true,
    fixture_types_read: true,
    fixture_types_write: true,
    task_templates_read: true,
    task_templates_write: true,
    areas_read: true,
    areas_write: true,
    areas_admin: true,
    area_templates_read: true,
    area_templates_read_by_type: true,
    area_templates_write: true,
    leads_read: true,
    leads_write: true,
    leads_admin: true,
    contacts_read: true,
    contacts_write: true,
    contacts_admin: true,
    accounts_read: true,
    accounts_write: true,
    accounts_admin: true,
    dashboard_read: true,
    facilities_read: true,
    facilities_write: true,
    facilities_admin: true,
    facility_tasks_read: true,
    facility_tasks_write: true,
    facility_tasks_admin: true,
    teams_admin: true,
    task_templates_admin: true,
    proposal_templates_admin: true,
    proposal_templates_delete: true,
    proposals_read: true,
    proposals_write: true,
    proposals_admin: true,
    proposals_delete: true,
    contracts_read: true,
    contracts_write: true,
    contracts_admin: true,
    crm: true,
    proposals: true,
    contracts: true,
    reporting: true,
    estimates: true,
    facilities: true,
    tasks: true,
    cleaners: true,
    jobs_read: true,
    jobs_write: true,
    jobs_admin: true,
    inspections_read: true,
    inspections_write: true,
    inspections_admin: true,
    time_tracking_read: true,
    time_tracking_write: true,
    time_tracking_approve: true,
    invoices_read: true,
    invoices_write: true,
    invoices_admin: true,
    quotations_read: true,
    quotations_write: true,
    quotations_admin: true,
    quotations_delete: true,
  },
  admin: {
    crm: true,
    proposals: true,
    contracts: true,
    reporting: true,
    users_read: true,
    users_write: true,
    settings_read: true,
    settings_write: true,
    pricing_read: true,
    pricing_write: true,
    teams_read: true,
    teams_write: true,
    proposal_templates_read: true,
    proposal_templates_write: true,
    area_types_manage: true,
    lead_sources_read: true,
    lead_sources_write: true,
    fixture_types_read: true,
    fixture_types_write: true,
    task_templates_read: true,
    task_templates_write: true,
    areas_read: true,
    areas_write: true,
    areas_admin: true,
    area_templates_read: true,
    area_templates_read_by_type: true,
    area_templates_write: true,
    leads_read: true,
    leads_write: true,
    leads_admin: true,
    contacts_read: true,
    contacts_write: true,
    contacts_admin: true,
    accounts_read: true,
    accounts_write: true,
    accounts_admin: true,
    dashboard_read: true,
    facilities_read: true,
    facilities_write: true,
    facilities_admin: true,
    facility_tasks_read: true,
    facility_tasks_write: true,
    facility_tasks_admin: true,
    teams_admin: true,
    task_templates_admin: true,
    proposal_templates_admin: true,
    proposals_read: true,
    proposals_write: true,
    proposals_admin: true,
    contracts_read: true,
    contracts_write: true,
    contracts_admin: true,
    facilities: true,
    estimates: true,
    jobs_read: true,
    jobs_write: true,
    jobs_admin: true,
    inspections_read: true,
    inspections_write: true,
    inspections_admin: true,
    time_tracking_read: true,
    time_tracking_write: true,
    time_tracking_approve: true,
    invoices_read: true,
    invoices_write: true,
    invoices_admin: true,
    quotations_read: true,
    quotations_write: true,
    quotations_admin: true,
  },
  manager: {
    estimates: true,
    facilities: true,
    tasks: true,
    cleaners: true,
    reports_read: true,
    users_read: true,
    settings_read: true,
    pricing_read: true,
    teams_read: true,
    teams_write: true,
    proposal_templates_read: true,
    proposal_templates_write: true,
    area_types_manage: true,
    lead_sources_read: true,
    fixture_types_read: true,
    task_templates_read: true,
    task_templates_write: true,
    areas_read: true,
    areas_write: true,
    area_templates_read_by_type: true,
    leads_read: true,
    leads_write: true,
    contacts_read: true,
    contacts_write: true,
    accounts_read: true,
    accounts_write: true,
    dashboard_read: true,
    facilities_read: true,
    facilities_write: true,
    facility_tasks_read: true,
    facility_tasks_write: true,
    proposals_read: true,
    proposals_write: true,
    contracts_read: true,
    contracts_write: true,
    jobs_read: true,
    jobs_write: true,
    inspections_read: true,
    inspections_write: true,
    time_tracking_read: true,
    time_tracking_write: true,
    time_tracking_approve: true,
    invoices_read: true,
    invoices_write: true,
    quotations_read: true,
    quotations_write: true,
  },
  cleaner: {
    work_orders: true,
    own_tasks_only: true,
    facilities_read: true,
    jobs_read: true,
    inspections_read: true,
    inspections_write: true,
    time_tracking_read: true,
    time_tracking_write: true,
  },
  subcontractor: {
    dashboard_read: true,
    contracts_read: true,
    facilities_read: true,
    jobs_read: true,
    jobs_write: true,
    time_tracking_read: true,
    time_tracking_write: true,
  },
};

export const ROLE_HIERARCHY: Record<UserRole, number> = {
  owner: 100,
  admin: 75,
  manager: 50,
  cleaner: 25,
  subcontractor: 10,
};

export function hasPermission(role: UserRole, permission: string): boolean {
  const permissions = rolePermissions[role];
  return permissions.all === true || permissions[permission] === true;
}

export function isRoleAtLeast(
  userRole: UserRole,
  requiredRole: UserRole
): boolean {
  return ROLE_HIERARCHY[userRole] >= ROLE_HIERARCHY[requiredRole];
}

export function resolveHighestRole(roles: UserRole[]): UserRole {
  if (roles.length === 0) {
    return 'cleaner';
  }

  return roles.reduce((highest, current) =>
    ROLE_HIERARCHY[current] > ROLE_HIERARCHY[highest] ? current : highest
  );
}

const VALID_ROLES: UserRole[] = ['owner', 'admin', 'manager', 'cleaner', 'subcontractor'];

export function isValidRole(role: unknown): role is UserRole {
  return typeof role === 'string' && VALID_ROLES.includes(role as UserRole);
}
