export interface ResidentialAreaTypeSeed {
  name: string;
  description: string;
  scope: 'residential' | 'both';
  guidanceItems: string[];
}

export interface ResidentialFixtureTypeSeed {
  name: string;
  category: 'fixture' | 'furniture';
}

export interface ResidentialTaskTemplateSeed {
  name: string;
  scope: 'residential' | 'both';
  cleaningType: string;
  areaTypeName: string;
  baseMinutes?: number;
  perSqftMinutes?: number;
  perUnitMinutes?: number;
  perRoomMinutes?: number;
  instructions: string;
}

// Task groupings are based on room-by-room residential cleaning checklists from:
// - Molly Maid house, kitchen, bathroom, bedroom, living room, and laundry guides
// - Merry Maids room-by-room and bedroom cleaning checklists
// - The Maids house cleaning checklist
export const RESIDENTIAL_AREA_TYPES: ResidentialAreaTypeSeed[] = [
  {
    name: 'Kitchen',
    description: 'Residential kitchen and food prep areas.',
    scope: 'both',
    guidanceItems: [
      'Counters and backsplash wiped clean',
      'Sink and faucet sanitized',
      'Appliance exteriors spot cleaned',
      'Cabinet fronts free of grease and fingerprints',
      'Floors swept and mopped',
      'Trash removed and liner replaced',
    ],
  },
  {
    name: 'Bathroom',
    description: 'Residential full bathrooms and shared bathrooms.',
    scope: 'residential',
    guidanceItems: [
      'Mirrors cleaned and streak-free',
      'Sink, vanity, and fixtures sanitized',
      'Toilet scrubbed and disinfected',
      'Tub and shower walls cleaned',
      'Floors mopped and edges detailed',
      'Trash removed and towels reset',
    ],
  },
  {
    name: 'Bedroom',
    description: 'Residential bedrooms, guest rooms, and sleeping areas.',
    scope: 'residential',
    guidanceItems: [
      'Bed made or linens changed',
      'Furniture and decor dusted',
      'Mirrors and glass spot cleaned',
      'High-touch surfaces sanitized',
      'Floors vacuumed or mopped',
      'Clutter picked up from visible surfaces',
    ],
  },
  {
    name: 'Living Room',
    description: 'Residential living rooms and formal sitting areas.',
    scope: 'residential',
    guidanceItems: [
      'Tables, shelves, and decor dusted',
      'High-touch surfaces sanitized',
      'Upholstery vacuumed',
      'Glass and mirrors cleaned',
      'Floors vacuumed or mopped',
      'Room straightened and cushions reset',
    ],
  },
  {
    name: 'Dining Room',
    description: 'Residential dining rooms and eating areas.',
    scope: 'residential',
    guidanceItems: [
      'Table and chairs wiped clean',
      'Light dust removed from surfaces',
      'Glass and mirrors spot cleaned',
      'Floors vacuumed or mopped',
      'Visible clutter removed',
    ],
  },
  {
    name: 'Laundry Room',
    description: 'Residential laundry rooms and utility wash areas.',
    scope: 'residential',
    guidanceItems: [
      'Washer and dryer exteriors wiped down',
      'Counters and sink cleaned',
      'Lint and debris removed',
      'Supplies organized',
      'Floors swept and mopped',
    ],
  },
  {
    name: 'Entryway',
    description: 'Residential entryways, foyers, and front-door landings.',
    scope: 'residential',
    guidanceItems: [
      'Entry glass and handles wiped down',
      'Shoes and clutter organized',
      'Surfaces dusted',
      'Floors vacuumed or mopped',
      'Cobwebs removed from corners',
    ],
  },
  {
    name: 'Mudroom',
    description: 'Residential mudrooms and back entry transition areas.',
    scope: 'residential',
    guidanceItems: [
      'Shoes and outerwear organized',
      'Benches and surfaces wiped down',
      'Visible dirt and debris removed',
      'Floors scrubbed or mopped',
      'High-touch surfaces sanitized',
    ],
  },
  {
    name: 'Hallway',
    description: 'Shared residential and commercial circulation hallways.',
    scope: 'both',
    guidanceItems: [
      'Floors clean and debris-free',
      'Baseboards and ledges dusted',
      'Switches and handles wiped',
      'Corners free of cobwebs',
      'Walls spot cleaned where needed',
    ],
  },
  {
    name: 'Staircase',
    description: 'Residential interior stairs, banisters, and landings.',
    scope: 'residential',
    guidanceItems: [
      'Treads vacuumed or wiped clean',
      'Banisters and railings wiped down',
      'Corners free of dust and debris',
      'Landings cleaned and clear',
      'Baseboards and risers spot cleaned',
    ],
  },
  {
    name: 'Home Office',
    description: 'Residential home office, study, or desk area.',
    scope: 'residential',
    guidanceItems: [
      'Desk and shelving dusted',
      'High-touch surfaces sanitized',
      'Glass and screens spot cleaned',
      'Visible clutter organized',
      'Floors vacuumed or mopped',
    ],
  },
  {
    name: 'Family Room',
    description: 'Residential family room, den, or media room.',
    scope: 'residential',
    guidanceItems: [
      'Furniture and electronics dusted',
      'High-touch surfaces sanitized',
      'Upholstery vacuumed',
      'Floors vacuumed or mopped',
      'Room straightened and cushions reset',
    ],
  },
  {
    name: 'Playroom',
    description: 'Residential playrooms and children activity spaces.',
    scope: 'residential',
    guidanceItems: [
      'Toys and visible clutter organized',
      'Shelves and surfaces wiped down',
      'High-touch surfaces sanitized',
      'Floors vacuumed or mopped',
      'Smudges cleaned from reachable walls and doors',
    ],
  },
  {
    name: 'Closet',
    description: 'Residential closets and wardrobe storage areas.',
    scope: 'residential',
    guidanceItems: [
      'Floor cleared and vacuumed',
      'Shelves dusted',
      'Cobwebs removed',
      'Visible items organized',
    ],
  },
  {
    name: 'Garage',
    description: 'Residential garages and enclosed parking storage spaces.',
    scope: 'residential',
    guidanceItems: [
      'Loose debris swept out',
      'Cobwebs removed from corners',
      'Visible clutter consolidated',
      'High-touch handles and switches wiped',
    ],
  },
  {
    name: 'Basement',
    description: 'Residential basements and lower-level flex spaces.',
    scope: 'residential',
    guidanceItems: [
      'Surfaces dusted',
      'Floors vacuumed or swept',
      'Cobwebs removed',
      'High-touch surfaces wiped down',
      'Visible clutter organized',
    ],
  },
  {
    name: 'Patio / Balcony',
    description: 'Residential patios, balconies, and small outdoor living areas.',
    scope: 'residential',
    guidanceItems: [
      'Loose debris swept away',
      'Railings and reachable surfaces wiped down',
      'Glass doors spot cleaned',
      'Cobwebs removed from corners',
    ],
  },
];

export const RESIDENTIAL_FIXTURE_TYPES: ResidentialFixtureTypeSeed[] = [
  { name: 'Bathtub', category: 'fixture' },
  { name: 'Bed', category: 'furniture' },
  { name: 'Dining Chair', category: 'furniture' },
  { name: 'Dining Table', category: 'furniture' },
  { name: 'Dresser', category: 'furniture' },
  { name: 'Dryer', category: 'fixture' },
  { name: 'Nightstand', category: 'furniture' },
  { name: 'TV Stand', category: 'furniture' },
  { name: 'Vanity', category: 'fixture' },
  { name: 'Washer', category: 'fixture' },
];

export const RESIDENTIAL_TASK_TEMPLATE_SEEDS: ResidentialTaskTemplateSeed[] = [
  {
    name: 'Clear And Wipe Countertops',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Kitchen',
    perRoomMinutes: 7,
    instructions: 'Remove visible debris, wipe counters, and spot clean backsplash areas.',
  },
  {
    name: 'Wipe Cabinet Fronts And Pulls',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Kitchen',
    perRoomMinutes: 6,
    instructions: 'Wipe exterior cabinet faces and pulls to remove fingerprints and grease.',
  },
  {
    name: 'Clean Appliance Exteriors And Stovetop',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Kitchen',
    perRoomMinutes: 8,
    instructions: 'Wipe exterior appliances and clean the stovetop surface.',
  },
  {
    name: 'Sanitize Sink And Faucet',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Kitchen',
    perRoomMinutes: 4,
    instructions: 'Scrub the sink basin, faucet, and surrounding edges, then dry to reduce spotting.',
  },
  {
    name: 'Sweep And Mop Kitchen Floors',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Kitchen',
    perRoomMinutes: 8,
    instructions: 'Sweep debris from corners and mop hard floors from back to front.',
  },
  {
    name: 'Empty Kitchen Trash And Replace Liner',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Kitchen',
    perRoomMinutes: 2,
    instructions: 'Remove trash, replace liner, and wipe the bin rim if needed.',
  },
  {
    name: 'Clean Microwave Interior And Exterior',
    scope: 'both',
    cleaningType: 'deep_clean',
    areaTypeName: 'Kitchen',
    perRoomMinutes: 6,
    instructions: 'Clean splatter and residue from the inside and outside of the microwave.',
  },
  {
    name: 'Scrub Toilet And Disinfect Touchpoints',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bathroom',
    perRoomMinutes: 10,
    instructions: 'Scrub the bowl and disinfect the seat, base, handle, and surrounding touchpoints.',
  },
  {
    name: 'Clean Vanity, Sink, And Faucet',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bathroom',
    perRoomMinutes: 8,
    instructions: 'Wipe the vanity, sink basin, countertop, and faucet with bathroom-safe cleaner.',
  },
  {
    name: 'Polish Mirrors And Glass',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bathroom',
    perRoomMinutes: 4,
    instructions: 'Clean mirrors and glass surfaces until streak-free.',
  },
  {
    name: 'Scrub Tub And Shower Walls',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bathroom',
    perRoomMinutes: 12,
    instructions: 'Scrub tub, shower walls, and fixtures to remove soap residue and buildup.',
  },
  {
    name: 'Mop Bathroom Floor And Edges',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bathroom',
    perRoomMinutes: 6,
    instructions: 'Sweep first, then mop the bathroom floor with extra attention around edges.',
  },
  {
    name: 'Remove Bathroom Trash And Reset Towels',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bathroom',
    perRoomMinutes: 3,
    instructions: 'Remove trash, replace liner if needed, and neatly reset towels.',
  },
  {
    name: 'Detail Grout, Tracks, And Baseboards',
    scope: 'residential',
    cleaningType: 'deep_clean',
    areaTypeName: 'Bathroom',
    perRoomMinutes: 10,
    instructions: 'Detail grout lines, shower tracks, and baseboards to remove heavier buildup.',
  },
  {
    name: 'Make Bed And Tidy Surfaces',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bedroom',
    perRoomMinutes: 6,
    instructions: 'Make the bed and straighten visible surfaces for a tidy finish.',
  },
  {
    name: 'Dust Furniture, Shelves, And Decor',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bedroom',
    perRoomMinutes: 8,
    instructions: 'Dust dressers, nightstands, shelves, and decor from top to bottom.',
  },
  {
    name: 'Clean Mirrors And Glass Surfaces',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bedroom',
    perRoomMinutes: 4,
    instructions: 'Spot clean mirrors, glass tabletops, and reachable windows as needed.',
  },
  {
    name: 'Sanitize Switches, Handles, And Touchpoints',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bedroom',
    perRoomMinutes: 3,
    instructions: 'Disinfect switches, handles, knobs, and other common touchpoints.',
  },
  {
    name: 'Vacuum Or Mop Bedroom Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bedroom',
    perRoomMinutes: 10,
    instructions: 'Vacuum carpet or sweep and mop hard floors, including under bed edges.',
  },
  {
    name: 'Change Bed Linens',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Bedroom',
    perRoomMinutes: 8,
    instructions: 'Strip used linens and remake the bed with fresh sheets when requested.',
  },
  {
    name: 'Vacuum Mattress And Detail Baseboards',
    scope: 'residential',
    cleaningType: 'deep_clean',
    areaTypeName: 'Bedroom',
    perRoomMinutes: 10,
    instructions: 'Vacuum the mattress surface and detail baseboards and hard-to-reach edges.',
  },
  {
    name: 'Straighten Cushions And Declutter Surfaces',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Living Room',
    perRoomMinutes: 5,
    instructions: 'Reset cushions, fold throws, and clear visible clutter from tables and shelves.',
  },
  {
    name: 'Dust Furniture, Shelves, And Decor',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Living Room',
    perRoomMinutes: 8,
    instructions: 'Dust tables, shelving, electronics, and decor from top to bottom.',
  },
  {
    name: 'Disinfect Remotes And High-Touch Surfaces',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Living Room',
    perRoomMinutes: 3,
    instructions: 'Wipe remotes, switches, handles, and other high-touch surfaces with disinfectant.',
  },
  {
    name: 'Vacuum Upholstery And Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Living Room',
    perRoomMinutes: 12,
    instructions: 'Vacuum upholstery, rugs, and floor edges using attachments where needed.',
  },
  {
    name: 'Clean Glass, Mirrors, And Tabletops',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Living Room',
    perRoomMinutes: 5,
    instructions: 'Spot clean mirrors, glass, and tabletop surfaces for a streak-free finish.',
  },
  {
    name: 'Mop Hard Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Living Room',
    perRoomMinutes: 8,
    instructions: 'Sweep or vacuum first, then mop hard floors thoroughly.',
  },
  {
    name: 'Detail Baseboards, Blinds, And Fan Blades',
    scope: 'residential',
    cleaningType: 'deep_clean',
    areaTypeName: 'Living Room',
    perRoomMinutes: 10,
    instructions: 'Detail baseboards, blinds, fan blades, and other higher dust-collecting surfaces.',
  },
  {
    name: 'Wipe Dining Table And Chairs',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Dining Room',
    perRoomMinutes: 6,
    instructions: 'Wipe the dining table, chair backs, and chair legs to remove dust and food residue.',
  },
  {
    name: 'Dust Surfaces And Light Decor',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Dining Room',
    perRoomMinutes: 5,
    instructions: 'Dust buffets, shelves, frames, and visible decor items.',
  },
  {
    name: 'Spot Clean Glass And Mirrors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Dining Room',
    perRoomMinutes: 3,
    instructions: 'Spot clean mirrors, glass doors, and glass tabletops as needed.',
  },
  {
    name: 'Vacuum Or Mop Dining Room Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Dining Room',
    perRoomMinutes: 7,
    instructions: 'Vacuum or sweep under the table and chairs, then mop hard floors if applicable.',
  },
  {
    name: 'Wipe Washer And Dryer Exteriors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Laundry Room',
    perRoomMinutes: 5,
    instructions: 'Wipe exterior surfaces of the washer and dryer and clean nearby controls.',
  },
  {
    name: 'Clean Utility Sink And Counters',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Laundry Room',
    perRoomMinutes: 6,
    instructions: 'Scrub the sink and wipe laundry counters and folding surfaces.',
  },
  {
    name: 'Sweep And Mop Laundry Room Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Laundry Room',
    perRoomMinutes: 6,
    instructions: 'Sweep away lint and debris, then mop hard floors.',
  },
  {
    name: 'Empty Lint And Visible Debris',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Laundry Room',
    perRoomMinutes: 3,
    instructions: 'Remove visible lint and debris from surfaces and the surrounding floor area.',
  },
  {
    name: 'Detail Lint Trap Area And Baseboards',
    scope: 'residential',
    cleaningType: 'deep_clean',
    areaTypeName: 'Laundry Room',
    perRoomMinutes: 6,
    instructions: 'Detail around the lint trap, dryer edges, and baseboards where dust gathers.',
  },
  {
    name: 'Organize Shoes And Visible Clutter',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Entryway',
    perRoomMinutes: 4,
    instructions: 'Straighten shoes, mats, and visible clutter near the entrance.',
  },
  {
    name: 'Wipe Entry Door Glass, Handles, And Trim',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Entryway',
    perRoomMinutes: 5,
    instructions: 'Clean entry glass and wipe handles, trim, and adjacent switch plates.',
  },
  {
    name: 'Vacuum Or Mop Entry Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Entryway',
    perRoomMinutes: 6,
    instructions: 'Vacuum or sweep away tracked-in debris, then mop hard floors if needed.',
  },
  {
    name: 'Wipe Benches, Cubbies, And Touchpoints',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Mudroom',
    perRoomMinutes: 6,
    instructions: 'Wipe benches, storage cubbies, hooks, and other common touchpoints.',
  },
  {
    name: 'Sweep And Mop Mudroom Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Mudroom',
    perRoomMinutes: 7,
    instructions: 'Sweep up dirt and grit, then mop the floor thoroughly.',
  },
  {
    name: 'Dust Ledges, Baseboards, And Corners',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Hallway',
    perRoomMinutes: 5,
    instructions: 'Dust ledges, baseboards, and corners where debris and cobwebs collect.',
  },
  {
    name: 'Vacuum Or Mop Hallway Floors',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Hallway',
    perRoomMinutes: 7,
    instructions: 'Vacuum carpets or sweep and mop hard hallway floors end to end.',
  },
  {
    name: 'Wipe Handrails, Switches, And Door Handles',
    scope: 'both',
    cleaningType: 'weekly',
    areaTypeName: 'Hallway',
    perRoomMinutes: 4,
    instructions: 'Disinfect frequently touched surfaces throughout the hallway.',
  },
  {
    name: 'Dust Banisters And Railings',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Staircase',
    perRoomMinutes: 5,
    instructions: 'Dust and wipe banisters, railings, and newel posts.',
  },
  {
    name: 'Vacuum Or Wipe Stair Treads And Risers',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Staircase',
    perRoomMinutes: 7,
    instructions: 'Clean stair treads, risers, and edges with the appropriate floor method.',
  },
  {
    name: 'Dust Desk, Shelves, And Decor',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Home Office',
    perRoomMinutes: 7,
    instructions: 'Dust desks, shelving, and decor while avoiding disruption of paperwork.',
  },
  {
    name: 'Wipe Electronics And Touchpoints',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Home Office',
    perRoomMinutes: 4,
    instructions: 'Wipe reachable electronics, switches, handles, and touchpoints carefully.',
  },
  {
    name: 'Vacuum Or Mop Office Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Home Office',
    perRoomMinutes: 7,
    instructions: 'Vacuum carpets or sweep and mop hard floors, including edges.',
  },
  {
    name: 'Dust Furniture And Electronics',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Family Room',
    perRoomMinutes: 8,
    instructions: 'Dust furniture, electronics, and decor surfaces throughout the room.',
  },
  {
    name: 'Vacuum Upholstery And Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Family Room',
    perRoomMinutes: 12,
    instructions: 'Vacuum upholstered seating, rugs, and the floor perimeter.',
  },
  {
    name: 'Organize Toys And Wipe Surfaces',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Playroom',
    perRoomMinutes: 8,
    instructions: 'Organize visible toys and wipe accessible play surfaces and shelving.',
  },
  {
    name: 'Vacuum Or Mop Playroom Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Playroom',
    perRoomMinutes: 8,
    instructions: 'Vacuum or mop floors, including corners and edges where debris gathers.',
  },
  {
    name: 'Dust Shelves And Clear Closet Floor',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Closet',
    perRoomMinutes: 5,
    instructions: 'Dust shelves and clear the visible closet floor for vacuuming or sweeping.',
  },
  {
    name: 'Sweep Garage Floor And Remove Cobwebs',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Garage',
    perRoomMinutes: 9,
    instructions: 'Sweep loose debris from the garage floor and remove cobwebs from corners.',
  },
  {
    name: 'Dust Surfaces And Sweep Basement Floors',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Basement',
    perRoomMinutes: 9,
    instructions: 'Dust reachable surfaces and sweep or vacuum basement floors and edges.',
  },
  {
    name: 'Sweep Patio Or Balcony And Wipe Railings',
    scope: 'residential',
    cleaningType: 'weekly',
    areaTypeName: 'Patio / Balcony',
    perRoomMinutes: 8,
    instructions: 'Sweep debris and wipe railings and reachable outdoor surfaces.',
  },
];

export const RESIDENTIAL_AREA_TEMPLATE_FIXTURES: Record<string, string[]> = {
  Bathroom: ['Toilet', 'Sink', 'Faucet', 'Mirror', 'Bathtub', 'Vanity', 'Trash Can'],
  Bedroom: ['Bed', 'Nightstand', 'Dresser', 'Window'],
  'Dining Room': ['Dining Table', 'Dining Chair', 'Window'],
  Entryway: ['Bench', 'Mirror', 'Glass Door'],
  'Family Room': ['Sofa', 'Coffee Table', 'Side Table', 'Wall Mounted TV', 'Window'],
  Garage: ['Storage Cabinet'],
  Hallway: ['Light Fixture', 'Window'],
  'Home Office': ['Desk', 'Office Chair', 'Bookcase', 'Window'],
  Kitchen: ['Sink', 'Faucet', 'Trash Can', 'Window'],
  'Laundry Room': ['Washer', 'Dryer', 'Sink', 'Faucet'],
  'Living Room': ['Sofa', 'Coffee Table', 'Side Table', 'TV Stand', 'Window'],
  Mudroom: ['Bench', 'Storage Cabinet'],
  Playroom: ['Storage Cabinet', 'Window'],
  Staircase: ['Light Fixture'],
};
